name: Continuous Integration

on: [push]

jobs:
   mypy:
    name: mypy check
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install mypy
      run: |
        cat scripts/requirements_dev.txt | grep "mypy" | xargs pip install
    - name: Check
      run: |
        scripts/mypy.sh --version
        scripts/mypy.sh

  ubuntu-unit-test:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mpi-vendor: ['openmpi', 'mpich']
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MPI
      run: ./scripts/install_mpi.sh ${{ matrix.mpi-vendor }}
    - name: Install BlueFog
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        git submodule update --init --recursive
        python -m pip install -e .
    - name: Record Version
      run: |
        gcc --version
        python --version
        mpiexec --version
        pip list
    - name: Unit Test
      run: make test_torch_basic test_torch_ops test_torch_hier_ops
      
  macos-unit-test:
    
    runs-on: macos-10.15
    strategy:
      matrix:
        mpi-vendor: ['openmpi', 'mpich']
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MPI
      run: ./scripts/install_mpi.sh ${{ matrix.mpi-vendor }}
    - name: Install BlueFog
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        git submodule update --init --recursive
        python -m pip install -e .
    - name: Record Version
      run: |
        gcc --version
        python --version
        mpiexec --version
        pip list
    - name: Unit Test
      run: OVERSUBSCRIBE=1 make test_torch_basic test_torch_hier_ops test_torch_ops test_torch_win_ops