name: Docu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-page:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build Document
      run: |
        python -m pip install -r requirements.txt
        python -m pip install matplotlib sphinx sphinx_rtd_theme torch
        cd docs && make html
        touch _build/html/.nojekyll
    - name: Deploy Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
